stages:
  - build
  - test
  #- deploy

image: docker:stable

services:
  - docker:dind

variables:
  - DOCKER_HUB_USER: $DOCKER_HUB_USER
  - DOCKER_HUB_PASSWORD: $DOCKER_HUB_PASSWORD
  - PROJECT_NAME: $DOCKER_HUB_USER/fellipe-gces-entrega02

before_script:
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin

test-backend:
  stage: test
  image: docker/compose:stable
  before_script:
    - echo "TESTING BACKEND . . ."
  script:
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "BACKEND SUCCESSFULLY TESTED."

test-frontend:
  stage: test
  image: docker/compose:stable
  before_script:
    - echo "TESTING FRONTEND . . ."
  script:
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "FRONTEND SUCCESSFULLY TESTED."

build-backend:
  stage: build
  before_script:
    - echo "BUILDING FRONTEND . . ."
  script:
    - docker build -f ./backend/Dockerfile -t $PROJECT_NAME:build-back ./backend
  after_script:
    - echo "BACKEND SUCCESSFULLY BUILT"