stages:
  - build
  - test
  #- deploy

image: docker:stable

services:
  - docker:dind

variables:
  - DOCKER_USER: $docker_user
  - DOCKER_PASSWORD: $docker_password
  - PROJECT_NAME: $docker_user/fellipe-gces-entrega02

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin